base_model: Qwen/Qwen-14B
base_model_config: Qwen/Qwen-14B
is_llama_derived_model: false
model_type: qwen
load_in_8bit: false
load_in_4bit: false
strict: false
# 可以采用不同的格式共同训练
# /home/LeiFeng/lzy/axolotl/src/axolotl/utils/data.py
# d_base_type:d_prompt_style 
# /home/LeiFeng/lzy/axolotl/src/axolotl/datasets.py: TokenizedPromptDataset.process
datasets:
  - path: /data/dataset/cciip-gpt/teknium_gpt4_teacher.jsonl
    type: sharegpt
    conversation: chatml
  - path: /data/dataset/cciip-gpt/teknium_gpt4_llm.jsonl
    type: sharegpt
    conversation: chatml
  - path: /data/dataset/cciip-gpt/slim_orca_dedup.jsonl
    type: sharegpt
    conversation: chatml
  - path: /data/dataset/cciip-gpt/map_coig_cqia.jsonl
    type: sharegpt
    conversation: chatml
  - path: /data/dataset/cciip-gpt/h4_no_robots.jsonl
    type: sharegpt
    conversation: chatml
  - path: /data/dataset/cciip-gpt/teknium_dataforg_economics.jsonl
    type: sharegpt
    conversation: chatml
  - path: /data/dataset/cciip-gpt/sharegpt4.jsonl
    type: sharegpt
    conversation: chatml
dataset_prepared_path: 
val_set_size: 0
output_dir: 

sequence_len: 4096
sample_packing: true
pad_to_sequence_len: true

adapter:
lora_model_dir:
lora_r:
lora_alpha:
lora_dropout:
lora_target_linear:
lora_fan_in_fan_out:

wandb_project: qwen
wandb_entity:
wandb_watch:
wandb_run_id:
wandb_log_model:

gradient_accumulation_steps: 2
micro_batch_size: 1
num_epochs: 3
optimizer: paged_adamw_32bit
lr_scheduler: cosine
learning_rate: 0.0002 # for llama: 3.0e-4, for mistral: 5.0e-5

train_on_inputs: false
group_by_length: false
bf16: true
fp16: false
tf32: false

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true

warmup_steps: 
eval_steps: 
eval_table_size:
save_steps: 300 
debug:
deepspeed: deepspeed/zero2.json
weight_decay: 0.0
fsdp:
fsdp_config:
special_tokens:
  eos_token: '<|endoftext|>'
  pad_token: '<|endoftext|>'